### ISSUE TITLE
[PE-D][Tester B] Error meesage could be misunderstood

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-2/tp#118]
![image.png](https://raw.githubusercontent.com/Hibeom0929/ped/main/files/de46a778-436c-4634-803f-8e2a53d6e28a.png)

For this error message, it says "it should not be blank", but the grade is an optional thing to add. Thus users might misunderstand as grade is not optional.

Same for pa/ at/ s/.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Hibeom0929/ped#8

**Comment by AL-ZT** [comment]
Edit command requires one optional field as stated in the user guide. If the grade prefix is specified, it is expected of the user to input a grade.
