### ISSUE TITLE
[PE-D][Tester C] History 1 Command does not Work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-2/tp#128]
When entering the command `history 1`, it lists all students

![image.png](https://raw.githubusercontent.com/theman-oj10/ped/main/files/bce2565a-eb54-4f7d-aeda-fe6bd9807485.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: theman-oj10/ped#1

**Comment by AL-ZT** [comment]
See #128
