### ISSUE TITLE
[PE-D][Tester A] Can spam open same student's note

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-2/tp#143]
**Steps to reproduce**
1. Click to open student 1's notes
2. Click to open student 2's notes
3. Click to open student 1's notes

**Expected**
Either only 1 student's notes to be shown/Only 1 of each student's notes to be shown

**Actual**
Multiple of the same student's notes shown

![Screenshot 2024-04-05 at 5.19.28 PM.png](https://raw.githubusercontent.com/Emberlynn-Loo/ped/main/files/19c608a2-7a5b-47f0-8bd6-81b3dfdf24ce.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Emberlynn-Loo/ped#9

**Comment by gowthaman-01** [comment]
Unable to replicate issue, with steps provided. 

https://github.com/AY2324S2-CS2103-F15-2/tp/assets/77627894/ae7ee0b3-e975-4e2f-8721-1d78ef198d35
