### ISSUE TITLE
[PE-D][Tester B] Redundant command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-2/tp#147]
Basically, the payment command and the filter command are doing almost the same thing. So it would be better to put the feature of the payment command in the filter command.

Also, they are very similar for find keyword also. Users may be confused what should they use if there are many different commands that work similarly.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Hibeom0929/ped#16

**Comment by Hwww23** [comment]
feature flaw
