### ISSUE TITLE
[PE-D][Tester C] Extra arguments are allowed in most commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-2/tp#163]
In commands such as `list`, `view`, `clear`, `exit`, and so on users can enter additional parameters and the command is still considered valid. Throwing an error can reduce confusion for the user as a user might think they might've added a parameter and be confused about its effect on the search results.

![image.png](https://raw.githubusercontent.com/theman-oj10/ped/main/files/d3358b30-535e-428c-a007-a263b91b7df0.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: theman-oj10/ped#20

**Comment by AL-ZT** [comment]
extraneous parameters for commands that do not take in parameters were already noted in the `Features` section of User guide.
