### ISSUE TITLE
DuplicateDateTimeException with no addressbook.json

### ISSUE THREAD

**Issue by AL-ZT** [AY2324S2-CS2103-F15-2/tp#76]
Hadn't actually run the program prior to today, but I had no display in the program with my old json data, as shown below.
![image](https://github.com/AY2324S2-CS2103-F15-2/tp/assets/111115885/81184e4d-9868-45ee-92d4-206565dfdd89)

When I tried to delete addressbook.json to repopulate the default data, this exception pops up.
![image](https://github.com/AY2324S2-CS2103-F15-2/tp/assets/111115885/d426797f-2321-4769-a476-4d4795d9ff05)

Not sure if its something on my side. You might want to duplicate your addressbook.json if you wish to replicate this issue.

**Comment by Hwww23** [comment]
{
  "persons" : [ {
    "name" : "John Doe",
    "phone" : "98765432",
    "email" : "johnd@example.com",
    "address" : "John street, block 123, #01-01",
    "grade" : "B+",
    "subject" : "Mathematics",
    "attendance" : "present",
    "payment" : "paid",
    "dateTimes" : [ "2024-02-03 2000" ],
    "tags" : [ ]
  }, {
    "name" : "John Doe7",
    "phone" : "98765432",
    "email" : "johnd@example.com",
    "address" : "John street, block 123, #01-01",
    "grade" : "-",
    "subject" : "No subject",
    "attendance" : "present",
    "payment" : "paid",
    "dateTimes" : [ "2024-02-03 1900" ],
    "tags" : [ ]
  }, {
    "name" : "John Doe8",
    "phone" : "98765432",
    "email" : "johnd@example.com",
    "address" : "John street, block 123, #01-01",
    "grade" : "-",
    "subject" : "No subject",
    "attendance" : "present",
    "payment" : "paid",
    "dateTimes" : [ "2024-02-03 0438" ],
    "tags" : [ ]
  }, {
    "name" : "John Doe9",
    "phone" : "98765432",
    "email" : "johnd@example.com",
    "address" : "John street, block 123, #01-01",
    "grade" : "-",
    "subject" : "No subject",
    "attendance" : "present",
    "payment" : "paid",
    "dateTimes" : [ "2024-02-03 0905" ],
    "tags" : [ ]
  }, {
    "name" : "John Doe2",
    "phone" : "98765432",
    "email" : "johnd@example.com",
    "address" : "John street, block 123, #01-01",
    "grade" : "-",
    "subject" : "No subject",
    "attendance" : "present",
    "payment" : "paid",
    "dateTimes" : [ ],
    "tags" : [ ]
  } ]
}

This is what I have in my current addressbok.json, the issue could be faced by having duplicatedatetime from the original data when initializing, hopefully this resolves the issue

**Comment by AL-ZT** [comment]
Thanks, resolved.
